export const vocabularyWords = [
  {
    id: 1,
    word: "methodology",
    pronunciation: "/mɛθəˈdɒlədʒi/",
    definition: "特定の研究分野や活動で使用される方法のシステム",
    difficulty: "intermediate",
    category: "research",
    mastery: 85,
    examples: ["研究方法論は論文で明確に概説されていた。"],
    dateAdded: "2024-01-15",
    source: "学術論文 #1",
    tags: ["研究", "学術", "科学"],
  },
  {
    id: 2,
    word: "paradigm",
    pronunciation: "/ˈpærəˌdaɪm/",
    definition: "何かの典型的な例やパターン；モデル",
    difficulty: "advanced",
    category: "academic",
    mastery: 72,
    examples: ["これは科学的思考のパラダイムシフトを表している。"],
    dateAdded: "2024-01-14",
    source: "研究記事",
    tags: ["理論", "モデル", "概念"],
  },
  {
    id: 3,
    word: "empirical",
    pronunciation: "/ɪmˈpɪrɪkəl/",
    definition: "観察や経験に基づく、またはそれによって検証可能な",
    difficulty: "advanced",
    category: "research",
    mastery: 91,
    examples: ["この研究は仮説に対する実証的証拠を提供している。"],
    dateAdded: "2024-01-13",
    source: "科学ジャーナル",
    tags: ["証拠", "観察", "データ"],
  },
  {
    id: 4,
    word: "hypothesis",
    pronunciation: "/haɪˈpɒθəsɪs/",
    definition: "限られた証拠に基づいて作られた仮定や提案された説明",
    difficulty: "intermediate",
    category: "research",
    mastery: 45,
    examples: ["仮説は制御された実験を通じてテストされた。"],
    dateAdded: "2024-01-12",
    source: "学術論文 #2",
    tags: ["理論", "予測", "科学"],
  },
];
